### ISSUE TITLE
Voeg peildatum toe aan settingspagina

### ISSUE THREAD

**Issue by peterboer** [Amsterdam/zaken-backend#1]
Nu filteren we enkel op begindatum van zaak, liever sorteert de projectmedewerker op alle open zaken na een specifieke begindatum (om niet al te oude zaken te tonen) èn na een specifieke peildatum. Toevoegen dus van peildatum aan filterset. Begindatum van een zaak wordt minder relevant zo, maar blijft  wel nodig om aan te geven. 

@petercuret _Check met Michael of wijzigingen de gewenste zaken opleveren_

**Comment by peterboer** [comment]
Checken met Michael (09/07/20)

**Comment by petercuret** [comment]
Checked and approved by Michael.
