### ISSUE TITLE
Tonen Invorderingen (Backend)

### ISSUE THREAD

**Issue by peterboer** [Amsterdam/zaken-backend#20]
- [x] Koppeling backend, endpoint met GET request
- [x] Koppeling frontend, tonen van invordering informatie
- [x] Check of kenmerk opleggen boete/invordering dwangsom in bwv aanwezig is
- [x] Push alle stadia vanuit TOP naar Zaken
- [x] Koppel Stadium kenmerk met invordering belastingdienst
- [x] Toevoegen huidige token op acceptance
- [x] Aanvraag SSL Certificate

**Comment by petercuret** [comment]
De backend koppeling is geïmplementeerd en staat op acceptatie.

Informatie over de informatie kan opgevraagd worden met een GET naar /api/v1/cases/{identification}/fines/
identification is het unieke kenmerk van de zaak (voorlopig nog de case_id van een zaak uit BWV)

Omdat er nog geen secret key is voor acceptatie acceptatie, zal daar de request mislukken.
@Jeffrey-Zutt  @gilleswittenberg Om door te ontikkelen op de frontend heb ik daarom een tijdelijk fallback gemaakt waarbij er bij een failed request altijd (anonieme) mock data teruggestuurd wordt.

**Comment by petercuret** [comment]
De kenmerk van een boete is een samenstelling van drie velden uit drie verschillende tabellen:
wng_id  _  wvs_nr _ sta_nr (zonder spaties)
wng_id: import_adres
wvs_nr: import_wvs
sta_nr: import_stadia

**Comment by petercuret** [comment]
Kenmerk wordt nu vanuit Top gegenereerd vanuit bestaande kolommen. Alle stadia komen nu ook mee (inclusief het invordering kenmerk) bij een push van Top naar Zaken-backend.
