### ISSUE TITLE
Doornemen documentatie BRP (Backend)

### ISSUE THREAD

**Issue by peterboer** [Amsterdam/zaken-backend#22]
BRP testdata is te vinden op gemeentelijke Sharefile (link bij @peterboer )

**Comment by petercuret** [comment]
@peterboer Ik heb de Excel even doorgenomen, en hier even mijn findings gedocumenteerd:

Als we op adresniveau hier toegang toe krijgen dan kunnen we TOP gelijk loskoppelen van de bwv_personen en bwv_personen_hist tabellen. 

Hierbij ga ik er wel van uit dat dan alleen levende en huidige bewoners meekomen, aangezien er geen vertrekdatum en overlijdingsdatum bij staat. Klopt dat?

BRP data die we ook in Top gebruiken:
- Achternaam/Geslachtsnaam
- Voornaam
- Geslachtsaanduiding
- Geboortedatum
- Datum inschrijving

Missende data:
- Vertrekdatum: _Dit is ook niet meer nodig als alleen de huidige bewoners uit het BRP komen_
- Overlijdingsdatum: _Soms staat er nog een persoon ingeschreven die al overleden is. Dan tonen we in Top nu een kruisje/datum. (Dit kunnen we doen omdat we dus de Overlijdingsdatum hebben)_
