### ISSUE TITLE
Typo field name `/api​/v1​/cases​/{identification}​/residents​/`

### ISSUE THREAD

**Issue by gilleswittenberg** [Amsterdam/zaken-backend#39]
There seems to be a typo in the `datum_begin_relatie_verblijadres` field. Should be `datum_begin_relatie_verblijfadres`. See: https://acc.looplijst.top.amsterdam.nl/api/v1/swagger/#/cases/cases_residents_retrieve

**Comment by xavierbloemen** [comment]
Fixed
